# check ./resee/utils/constant.py
seed: 42
sae_name: sae-DeepSeek-R1-Distill-Qwen-1.5B-65k
sae_hookpoint: model.layers.12

base_model_name: DeepSeek-R1-Distill-Qwen-1.5B
distill_type: sft_r1_distill
student_model_name: DeepSeek-R1-Distill-Qwen-1.5B
distill_dataset_name: curated_deepscaler
host_model_post_train_dataset_name: curated_deepscaler
host_model_post_train_type: grpo
host_model_checkpoint: checkpoint-2000

lora_r: 32
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- down_proj
- up_proj
- gate_proj
learning_rate: 1e-6
num_epochs: 2
batch_size: 1
logging_steps: 1
save_steps: 500
